<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <LangVersion>12</LangVersion>
        <Nullable>enable</Nullable>
        <RootNamespace>Accord.Transpiler</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AsmResolver.DotNet" Version="6.0.0-rc.1" />
    </ItemGroup>

</Project>
