<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>12</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Accord.Common\Accord.Common.csproj" />
        <ProjectReference Include="..\Accord.Generator\Accord.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />        <ProjectReference Include="..\Accord\Accord.csproj" />
    </ItemGroup>

</Project>
